### ISSUE TITLE
.NET Framework 4.7. 

### ISSUE THREAD

**Issue by xiaodongliang** [Developer-Autodesk/learn.forge.designautomation#11]
[http://learnforge.autodesk.io/#/designautomation/appbundle/engines/revit](http://learnforge.autodesk.io/#/designautomation/appbundle/engines/revit)
_The Please select .NET Framework 4.7. If not listed, please install._

The link downloads Runtime installer, not Developer pack which is required to be selected in Visual Studio new project dialog. It takes quite a long time (>20 min) to install and requires reboot 
of machine.

**Comment by augustogoncalves** [comment]
Isn't this the link: https://dotnet.microsoft.com/download/dotnet-framework/net47 ?

**Comment by augustogoncalves** [comment]
fixed on the tutorial (this is the sample).

**Comment by stonesthatwhisper** [comment]
@augustogoncalves This link opens a page with both Developer pack and Runtime download. Tutorial would better say the former (Developer pack) is desired.

**Comment by augustogoncalves** [comment]
thanks @stonesthatwhisper , fixed
