### ISSUE TITLE
Response status code does not indicate success: 401 (Unauthorized).

### ISSUE THREAD

**Issue by PavelBalobanov** [Developer-Autodesk/learn.forge.designautomation#13]
Hello!
When I launch the application  I see in my browser in the Configure window the list of AppBundles but I do not see the list of engines 
I tried to debug it and as it turned out in this row:

Page<string> engines = await _designAutomation.GetEnginesAsync()  

in Value column of the Watch window  I see this:

"The function evaluation requires all threads to run". 

When I step over\into this row it miss next rows of the code but  the application runs anyway. In the black window I see an error:

Hosting environment: Development
Content root path: C:\Users\admin\Documents\GitHub\learn.forge.designautomation\forgesample
Now listening on: http://localhost:3000
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLOEQ022D0V4", Request id "0HLOEQ022D0V4:00000001": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).

As I told when I tap Configure the window opens but there is no the list of engines..
Could you comment on this, please

Best regards,
Pavel

**Comment by augustogoncalves** [comment]
Hi Pavel

Please make sure you selected "Design Automation v3" at this step: http://learnforge.autodesk.io/#/account/?id=create-an-app

And have properly specified your Forge Client ID & Secret at this step: http://learnforge.autodesk.io/#/environment/setup/netcore_da?id=create-a-new-project-net-core

**Comment by PavelBalobanov** [comment]
Hi, thanks for the feedback!
I checked it. Yes, I selected design automation v3 and even hardcoded
client and secret id.

When I put them in the environment wrong in the previous row with
autentification I got an error “client and sever id do not fit”. But when I
hardcoded them I began taking token.
So everything you recommended I did before...

**Comment by PavelBalobanov** [comment]
That is what I get in this row
dynamic oauth = await OAuthController.GetInternalAsync();

oauth = {{"access_token":"eyJhbGciOiJIUzI1NiIsImtpZCI6Imp3dF9zeW1tZXRyaWNfa2V5In0.eyJjbGllbnRfaWQiOiJvTVc3MzlMN0hHNm44TzZHQlpwSEZBN1FKaW5qMHVVeiIsImV4cCI6MTU2Mzg5NjYzNSwic2NvcGUiOlsiYnVja2V0OmNyZWF0ZSIsImJ1Y2tldDpyZWFkIiwiYnVja2V0OmRlbGV0ZSIsImRhdGE6cmVhZCIsImRhdGE6d3JpdGUiLCJkYXRhOmNyZWF0ZSIsImNvZGU6YWxsIl0sImF1ZCI6Imh0dHBzOi8vYXV0b2Rlc2suY29tL2F1ZC9qd3RleHA2MCIsImp0aSI6IlZKbVVsbUlRVWRyODRScmpWZ3REMEJqU0FJQlkxbVhEcmR6emw0R1pRMVkyb09EWFhCenE5amNmdVRXdG52NW8ifQ.g8w9YTRia_yQeJfhF3XPxie3UHGpbkYTks2s-FVZcSw","token_type":"Bearer","expires_in":3599,"ExpiresAt":"2019-07-23T18:44:05.3941824+03:00"}}

**Comment by augustogoncalves** [comment]
can you please start a support ticket with forge.help@autodesk.com? Then we arrange a desktop sharing session. Thanks.

**Comment by PavelBalobanov** [comment]
Hi! Thanks for your quick feedbacks!
I did it, sent a message to the email you provided me with.
I know it is difficult to do for you... but what do you think if we can
have the meeting you proposed tomorrow or on Friday?

**Comment by augustogoncalves** [comment]
Solved via support.

**Comment by Sabareesh2805** [comment]
When I do a git bash, I am getting like below -

jsaba@LAPTOP-NVCEHSM2 MINGW64 ~/Desktop/KVB Materials and Income tax and reimbursements (master)
$ git push -u origin master
Select an authentication method for 'https://github.com/':
  1. Web browser (default)
  2. Personal access token
option (enter for default): 2
Enter GitHub personal access token for 'https://github.com/'...
Token:
fatal: Response status code does not indicate success: 401 (Unauthorized).
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/Sabareesh2805/gitcumjenkinsintegration.git/'

How to resolve this?

**Comment by Sabareesh2805** [comment]
Not able to perform token access

**Comment by augustogoncalves** [comment]
@Sabareesh2805 it doesn't look related to the sample.

**Comment by ShriramUltron** [comment]
@Sabareesh2805 sam eproblem, if u have resolved please do share the process

**Comment by petrbroz** [comment]
Please note that the Design Automation code sample has been migrated to https://github.com/autodesk-platform-services/aps-design-automation-nodejs and https://github.com/autodesk-platform-services/aps-design-automation-dotnet, and as part of the migration it's also been cleaned up a bit. If you still reproduce the issue with the new code, please report a bug in the new repository.
