### ISSUE TITLE
About text

### ISSUE THREAD

**Issue by jeanflowerADSK** [Developer-Autodesk/learn.forge.designautomation#19]
The About text for this repo doesn't mention nodejs.  Perhaps it should say:

About
Learn Forge Tutorial: Modify your models using Design Automation (AutoCAD, Inventor, Revit & 3dsMax). Available in .NET *and nodejs*.

This might seem like a small detail but having navigated from the nodejs link on this page,
https://learnforge.autodesk.io/#/tutorials/modifymodels
the About text made me wonder if I had landed in the right place.

**Comment by augustogoncalves** [comment]
Fixed. Thanks.
