### ISSUE TITLE
gitignore should ignore uploaded binaries

### ISSUE THREAD

**Issue by jeanflowerADSK** [Developer-Autodesk/learn.forge.designautomation#20]
Just a small issue, this one. Maybe a typo to fix in gitignore.

I'm following the nodejs tutorial and seeing binary files get added to a folder on my machine called 'uploads'.
The gitignore file names a folder to ignore called 'upload'.

Perhaps either the gitignore file should be changed, or this line in DesignAutomation.js?
router.post('/forge/designautomation/workitems', multer({
    dest: 'uploads/'

**Comment by augustogoncalves** [comment]
the .NET version deletes the file after uploading ([see here](https://github.com/Autodesk-Forge/learn.forge.designautomation/blob/master/forgesample/Controllers/DesignAutomationController.cs#L273))

the gitignore is a good suggestion, in case the code fails and the local copy is not deleted.

**Comment by libvarun** [comment]
it's there in gitignore file, just a spelling mistake, 'upload' should become 'uploads'

**Comment by libvarun** [comment]
https://github.com/Autodesk-Forge/learn.forge.designautomation/pull/23

**Comment by petrbroz** [comment]
Thanks Varun :+1:
