### ISSUE TITLE
README in nodejs branch should be branch-aware in the git instructions

### ISSUE THREAD

**Issue by jeanflowerADSK** [Developer-Autodesk/learn.forge.designautomation#21]
This suggestion could help people who aren't familiar with the branches that exist in this repo.  Following the instructions here
https://github.com/Autodesk-Forge/learn.forge.designautomation/tree/nodejs

I run the git clone invocation as suggested.  This generates files on my machine for the master branch.  I can't complete the next npm install instruction.

I suggest for the README in the nodejs branch, we add something like instructions to type
git checkout origin/nodejs
git branch nodejs

This helped me follow all the instructions until I started looking for the sample files.  They are in the master branch.
I don't know if there's a way to simplify this for people to ease the beginner path to success.

**Comment by libvarun** [comment]
https://github.com/Autodesk-Forge/learn.forge.designautomation/pull/22

**Comment by petrbroz** [comment]
Thanks for the info. I agree that having an explicit `git checkout` step mentioned in the README would be even better to make it clear that the code is actually available in a "special" branch.

Personally I think we should move away from this approach (keeping the client side code in _master_ and having specific language implementations branched off of it) entirely. It's starting to get really difficult to rebase the different branches. Let's discuss that after the Forge Training event.
